version: "3.7"

services:
  db:
    image: postgres
    container_name: database_ignite
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    ports:
      - 3333:3333
    volumes: 
      - .:/usr/app
volumes:
  pgdata:
    driver: local


